import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'projectStickFit.settings')
django.setup()

from projectStickFit.workouts.models import Exercises


def populate():
    exercises = [
        {"exercise_name": "Alternating one legged pushups (each leg)",
         "description": "Push-up variation where each leg is lifted alternately while performing push-ups."},
        {"exercise_name": "Alternating one-legged pike presses",
         "description": "Pike press with one leg raised alternately, targeting shoulders and core."},
        {"exercise_name": "Alternating seesaw lunges",
         "description": "Lunges with alternate stepping legs, emphasizing balance and leg strength."},
        {"exercise_name": "Arm Sweeps (each side)",
         "description": "Arm sweeps with controlled motion, focusing on shoulder mobility."},
        {"exercise_name": "Back plank",
         "description": "Plank position with back on the floor and legs raised, targeting core and glutes."},
        {"exercise_name": "Back plank twists",
         "description": "Twists in the back plank position, engaging the obliques."},
        {"exercise_name": "Base pogo",
         "description": "Small, rapid jumps in place, focusing on calf strength and explosive power."},
        {"exercise_name": "Bench dips",
         "description": "Tricep exercise using a bench for support, lowering the body and then pushing back up."},
        {"exercise_name": "Bent over L raises (robot)",
         "description": "Bent-over position with arms raised in an 'L' shape, working the shoulders."},
        {"exercise_name": "Bent over T raises",
         "description": "Arms raised in a 'T' shape while bent over, targeting the upper back."},
        {"exercise_name": "Bent over W raises",
         "description": "Bent-over arm raise in a 'W' shape, focusing on the upper back and shoulders."},
        {"exercise_name": "Bent over Y raises",
         "description": "Bent-over arm raises in a 'Y' shape to work the shoulders and upper back."},
        {"exercise_name": "Bicycle kicks",
         "description": "A core exercise simulating cycling motions, engaging the abdominals."},
        {"exercise_name": "Bodyweight squats",
         "description": "Basic squat exercise using body weight to strengthen legs and glutes."},
        {"exercise_name": "Box jumps",
         "description": "Jumping onto a box or platform, focusing on explosive power and leg strength."},
        {"exercise_name": "Burpee jump tucks",
         "description": "Burpee variation that includes a jump tuck for added intensity."},
        {"exercise_name": "Burpees", "description": "Full-body exercise involving a squat, push-up, and jump."},
        {"exercise_name": "Butt kicks",
         "description": "Jogging motion where heels kick the glutes, warming up the hamstrings."},
        {"exercise_name": "Crunches", "description": "Abdominal exercise focusing on contracting the core muscles."},
        {"exercise_name": "Drop squats",
         "description": "Squat variation with a quick drop into the squat position, increasing leg endurance."},
        {"exercise_name": "Elevated pushups",
         "description": "Push-up variation with hands elevated on a platform to target the upper chest."},
        {"exercise_name": "Face down back extensions",
         "description": "Back extension exercise performed while lying face down to strengthen the lower back."},
        {"exercise_name": "Fast feet in squat",
         "description": "Quickly shifting feet in a squat position to increase leg endurance."},
        {"exercise_name": "Fast feet on hands",
         "description": "Fast footwork while in a push-up position, improving hand and foot coordination."},
        {"exercise_name": "Floor bridges",
         "description": "Lifting the hips off the ground while lying on the floor, engaging the glutes."},
        {"exercise_name": "Floor crawl",
         "description": "Crawling on the floor using hands and feet to work the core and shoulders."},
        {"exercise_name": "Forearm plank",
         "description": "Plank position with forearms on the ground, targeting the core."},
        {"exercise_name": "Forearm plank pushups",
         "description": "Push-ups performed from the forearm plank position, targeting the core and chest."},
        {"exercise_name": "Forearm plank twists (each side)",
         "description": "Twists from a forearm plank position, engaging the obliques."},
        {"exercise_name": "Good mornings",
         "description": "A hinge movement to strengthen the lower back and hamstrings."},
        {"exercise_name": "Half pushups",
         "description": "A push-up variation where the arms are bent halfway, targeting the chest and arms."},
        {"exercise_name": "High knees",
         "description": "Running in place while lifting the knees as high as possible to engage the core."},
        {"exercise_name": "High plank",
         "description": "Standard plank position with hands on the ground, engaging the core and shoulders."},
        {"exercise_name": "High side plank (each side)",
         "description": "Side plank with elevated hips, focusing on obliques and shoulder stability."},
        {"exercise_name": "Hip hop mountain climbers",
         "description": "Mountain climbers performed with added hip movements, increasing the workout intensity."},
        {"exercise_name": "Hip hurdles",
         "description": "Jumping over an imaginary hurdle, working on agility and leg strength."},
        {"exercise_name": "Hop swaps",
         "description": "Jumping to alternate positions, increasing coordination and lower body power."},
        {"exercise_name": "Inchworm planks",
         "description": "Walk your hands out to a plank position, then walk your feet back in, engaging the core."},
        {"exercise_name": "Jumping Jack Crossovers",
         "description": "Jumping jacks with crossed arms, adding complexity to the traditional move."},
        {"exercise_name": "Jumping jacks",
         "description": "A cardio exercise involving jumping with legs and arms moving out and in."},
        {"exercise_name": "Kneeling pushups",
         "description": "Push-up variation performed on knees, lowering the intensity for beginners."},
        {"exercise_name": "Lateral low squats",
         "description": "Squat variation where you step side to side, engaging the inner thighs."},
        {"exercise_name": "Lateral plank walk",
         "description": "Plank position with sideways hand and foot movement, targeting the core."},
        {"exercise_name": "Low jacks",
         "description": "Jumping jacks performed with a lower squat position, adding intensity."},
        {"exercise_name": "Lunges",
         "description": "Leg exercise where one leg steps forward, engaging the glutes and thighs."},
        {"exercise_name": "Lying T raises",
         "description": "Lying on the stomach, lifting arms in a 'T' shape, targeting the shoulders."},
        {"exercise_name": "Mountain climber hops",
         "description": "A dynamic version of mountain climbers with added hopping motion for intensity."},
        {"exercise_name": "Mountain climbers",
         "description": "A full-body exercise involving alternating leg movements while in a plank position."},
        {"exercise_name": "Negative pushups",
         "description": "Push-ups where the focus is on the lowering phase, slowing down the descent."},
        {"exercise_name": "Offset pike presses (each side)",
         "description": "Pike press with one arm slightly offset, engaging the shoulders and core."},
        {"exercise_name": "One legged floor bridges (each side)",
         "description": "Floor bridges with one leg lifted, increasing glute and hamstring engagement."},
        {"exercise_name": "One-legged burpees (each side)",
         "description": "Burpee variation where one leg is lifted during the jump and push-up phases."},
        {"exercise_name": "One-legged mountain climbers (each side)",
         "description": "Mountain climbers with one leg lifted, alternating each side."},
        {"exercise_name": "One-legged pushups",
         "description": "Push-ups performed with one leg lifted to increase core stability."},
        {"exercise_name": "Palm pushes",
         "description": "A push-up variation performed with the palms, focusing on arm strength."},
        {"exercise_name": "Pike press",
         "description": "Shoulder press from a pike position, engaging the shoulders and upper back."},
        {"exercise_name": "Plank jacks",
         "description": "Plank position with feet jumping in and out, adding a cardio element."},
        {"exercise_name": "Plank to downward dogs",
         "description": "Transitioning from a plank position to a downward dog, focusing on core and shoulders."},
        {"exercise_name": "Plank twists",
         "description": "Twists performed in a plank position, engaging the obliques."},
        {"exercise_name": "Plyo pushups",
         "description": "Push-ups with an explosive motion, pushing the hands off the ground."},
        {"exercise_name": "Pogo jumps",
         "description": "Small, rapid jumps focusing on calf strength and quick leg movement."},
        {"exercise_name": "Power skips",
         "description": "Explosive skipping motion to improve leg power and coordination."},
        {"exercise_name": "Predator jacks",
         "description": "Jumping jacks with arm movements that mimic predator strikes."},
        {"exercise_name": "Prone W hold",
         "description": "Hold a 'W' position lying face down, engaging the upper back and shoulders."},
        {"exercise_name": "Pulse jump lunges",
         "description": "Lunge position with quick, small pulses and a jump for added intensity."},
        {"exercise_name": "Pushups",
         "description": "A fundamental upper-body exercise focusing on chest, arms, and core."},
        {"exercise_name": "Reach, roll and lifts (each side)",
         "description": "Core stability exercise involving reaching, rolling, and lifting motions."},
        {"exercise_name": "Reverse arm circles",
         "description": "Circular arm movements performed in reverse, warming up the shoulders."},
        {"exercise_name": "Reverse inchworms",
         "description": "Backward crawl movement to target the core and hamstrings."},
        {"exercise_name": "Reverse snow angels",
         "description": "Face-down arm movements mimicking snow angels, strengthening shoulders."},
        {"exercise_name": "Scap pushups",
         "description": "Push-ups emphasizing scapular motion to improve shoulder mobility."},
        {"exercise_name": "Seal jacks",
         "description": "Jumping jacks with arms clapping in front of the chest like a seal."},
        {"exercise_name": "Shadow boxing", "description": "Simulated boxing moves to improve cardio and coordination."},
        {"exercise_name": "Side to side base pogo", "description": "Small, lateral jumps for agility and leg power."},
        {"exercise_name": "Side to side scissor kick lifts",
         "description": "Core exercise with alternating side scissor kicks for oblique engagement."},
        {"exercise_name": "Side-lying leg lifts (each side)",
         "description": "Leg raises performed lying on one side to target the outer thighs."},
        {"exercise_name": "Single leg deadlifts (each leg)",
         "description": "Balance exercise targeting hamstrings and glutes with one leg raised."},
        {"exercise_name": "Single leg standing calf raises (each leg)",
         "description": "Calf raises on one leg to isolate and strengthen the calf muscles."},
        {"exercise_name": "Spidermans",
         "description": "Plank exercise bringing knees toward elbows for core and hip flexibility."},
        {"exercise_name": "Sprint in place",
         "description": "High-intensity running motion in one spot to boost cardio."},
        {"exercise_name": "Step down crossovers (each leg)",
         "description": "Controlled step-down with crossover motion to improve stability and coordination."},
        {"exercise_name": "Step ups", "description": "Stepping onto a raised surface to work glutes and thighs."},
        {"exercise_name": "Superman shoulder presses",
         "description": "Face-down shoulder presses in the superman position to engage the back."},
        {"exercise_name": "Superman swimmers",
         "description": "Alternating arm and leg movements in superman pose to target the lower back."},
        {"exercise_name": "Tuck jumps",
         "description": "Explosive jump bringing knees to the chest to build power and agility."},
        {"exercise_name": "Up downs",
         "description": "Dynamic movement alternating between standing and plank positions for cardio."},
        {"exercise_name": "V hold core crosses",
         "description": "Core exercise maintaining a 'V' position with crossing motions for added intensity."},
        {"exercise_name": "V ups", "description": "Core workout lifting the upper and lower body to form a 'V' shape."},
        {"exercise_name": "Wall rotators (each side)",
         "description": "Rotational stretches against a wall to enhance mobility and posture."},
        {"exercise_name": "Wall slides",
         "description": "Sliding arms up and down a wall to improve shoulder mobility and strength."},
    ]

    # Loop through the exercises and add them to the database
    for exercise in exercises:
        Exercises.objects.get_or_create(exercise_name=exercise["exercise_name"], description=exercise["description"])


if __name__ == '__main__':
    populate()
