# Generated by Django 5.1.3 on 2024-12-01 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appprofile',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(110), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
