# Generated by Django 5.1.3 on 2024-11-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='workout_type',
            field=models.CharField(choices=[('Total Body', 'Total Body'), ('Dynamic Balance', 'Dynamic Balance'), ('Muscle Focus', 'Muscle Focus')], default='Total Body'),
        ),
    ]
