# Generated by Django 5.1.3 on 2024-11-30 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumPost',
            new_name='ForumThreads',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='thread',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('thread', 'user')},
        ),
    ]
